name: Test install.sh on major Linux distros

on:
  push:
    paths:
      - .github/workflows/test-install.yml
  pull_request:
    paths:
      - .github/workflows/test-install.yml
  workflow_dispatch:

jobs:
  test-matrix:
    name: Test install.sh on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu:24.04
          - ubuntu:22.04
          - debian:bookworm
          - debian:bullseye
          - fedora:latest
          - archlinux:latest
          - alpine:latest
          - opensuse/leap
    steps:
      - name: Download install.sh from gist
        run: |
          curl -fsSL https://gist.githubusercontent.com/lowking/2ec5a67272df94235253632a10907ac4/raw/install.sh -o install.sh
          chmod +x install.sh
      - name: Set up docker container for ${{ matrix.distro }}
        run: |
          echo "FROM ${{ matrix.distro }}" > Dockerfile
          echo "COPY install.sh /install.sh" >> Dockerfile
          echo 'RUN chmod +x /install.sh' >> Dockerfile
          echo 'RUN export DEBIAN_FRONTEND=noninteractive' >> Dockerfile
          # 安装 sudo 等基础工具（必须在 root 下做！）
          echo 'RUN (command -v apt-get >/dev/null && apt-get update && apt-get install -y sudo git curl wget make gcc pkg-config build-essential || true)' >> Dockerfile
          echo 'RUN (command -v dnf >/dev/null && dnf install -y sudo git curl wget make gcc pkgconfig shadow-utils || true)' >> Dockerfile
          echo 'RUN (command -v yum >/dev/null && yum install -y sudo git curl wget make gcc pkgconfig shadow-utils || true)' >> Dockerfile
          echo 'RUN (command -v pacman >/dev/null && pacman -Sy --noconfirm sudo git curl wget make gcc pkgconf base-devel shadow || true)' >> Dockerfile
          echo 'RUN (command -v zypper >/dev/null && zypper --non-interactive install sudo git curl wget make gcc pkgconf shadow || true)' >> Dockerfile
          echo 'RUN (command -v apk >/dev/null && apk add --no-cache sudo git curl wget make gcc pkgconf build-base shadow || true)' >> Dockerfile
          # 创建 testuser 并赋予 sudo 权限
          echo 'RUN useradd -m testuser || adduser -D testuser || true' >> Dockerfile
          echo 'RUN echo "testuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers' >> Dockerfile
          echo 'USER testuser' >> Dockerfile
          echo 'WORKDIR /home/testuser' >> Dockerfile
      - name: Build the test container
        run: |
          SAFE_TAG=$(echo "${{ matrix.distro }}" | tr ':/' '-')
          docker build -t installsh-test:$SAFE_TAG .
      - name: Run install.sh in container
        run: |
          SAFE_TAG=$(echo "${{ matrix.distro }}" | tr ':/' '-')
          docker run --rm installsh-test:$SAFE_TAG sh -c "cd /home/testuser && sh /install.sh"
